# Generated by Django 4.0.3 on 2022-03-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_transcontinental_remove_country_continent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continent',
            old_name='continent',
            new_name='countries',
        ),
    ]
