# Generated by Django 4.0.3 on 2022-03-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_rename_continent_continent_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcontinental',
            old_name='main',
            new_name='main_continent',
        ),
    ]
