# Generated by Django 4.0.3 on 2022-03-21 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_rename_main_transcontinental_main_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AlterField(
            model_name='transcontinental',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.continent'),
        ),
        migrations.AlterField(
            model_name='transcontinental',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
    ]
