# Generated by Django 4.0.3 on 2022-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_city_is_country_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='land_area',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='land_area',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
