# Generated by Django 4.0.3 on 2022-03-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_continent_land_area_country_land_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='special_note',
            field=models.CharField(default='', max_length=100),
        ),
    ]
